### ISSUE TITLE
[feat]: Create Post API

### ISSUE THREAD

**Issue by csaba-nagy** [csaba-nagy/blog-adonis#51]
### Title

Create API for Posts

### Description

**To-Do:**
  - [x] Add routes for CRUD operations
  - [x] The create/update/delete operations should be available if the user is authenticated
  - [x] Post operations need to be authorized as follows:
 
  <details>
    <summary>See authorization rules</summary>

    - "AUTHOR" and "ADMIN" users can create new posts only
    - Posts are editable if their status is **not** "PUBLISHED"
    - The post's author and an admin can edit a post
    - The post's author can delete a post if the post status is **not** "PUBLISHED"
    - The "ADMIN" can delete a post with any status
    - Users can see posts if their status is "PUBLISHED"
    - "AUTHOR" can edit, delete, check its own posts if the post status is "DRAFT"
  </details>

  - [x] Write tests
